version: '3'
services:
    post:
        build: 
            context: ./app/post
            dockerfile: dockerfile.dev
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "4001:4001"
    comment:
        build: 
            context: ./app/comment
            dockerfile: dockerfile.dev
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "4002:4002"
    query:
        build: 
            context: ./app/query
            dockerfile: dockerfile.dev
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "4003:4003"
    mod:
        build: 
            context: ./app/moderation
            dockerfile: dockerfile.dev
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "4004:4004"
    event-bus:
        build: 
            context: ./app/event-bus
            dockerfile: dockerfile.dev
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "4005:4005"
    web:
        build: 
            context: ./app/web
            dockerfile: dockerfile.dev
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "3000:3000"
#     mariadb:
#         build:
#             context: ./mariadb
#             dockerfile: dockerfile
#         restart: unless-stopped
#         command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#         environment:
#             MARIADB_ROOT_PASSWORD: password
#             MARIADB_USER: dbadmin
#             MARIADB_PASSWORD: password
#             MARIADB_DATABASE: soccer
#         volumes:
#             - db_data:/var/lib/mysql
#  #           - ./mariadb/dump:/docker-entrypoint-initdb.d
#         expose:
#             - "3306"
#     phpmyadmin:
#         image: phpmyadmin
#         restart: unless-stopped
#         depends_on: 
#             - mariadb
#         environment:
#             - PMA_HOSTS=db
#         ports:
#             - "8888:80"
    
                    
networks:
    default:
        external: true
        name: tuxtum
volumes:
    db_data:
